### ISSUE TITLE
Spulen von Aufnahmen bei odroidn2+ geht nicht

### ISSUE THREAD

**Issue by rofehr** [rellla/vdr-plugin-softhddevice-drm-gles#4]
Beim spulen von Aufhahmen kommt immer folgenden Fehler Meldung
Jun 13 20:49:40 MLD vdr[7425]: [7828] animator thread thread started (pid=7425, tid=7828, prio=high)
Jun 13 20:49:40 MLD kernel: meson-vdec ff620000.video-decoder: Buffer 1 done but it doesn't exist in m2m_ctx
Jun 13 20:49:40 MLD vdr[7425]: [7458] SVDRP MLD < 127.0.0.1:38620 client connection accepted
Jun 13 20:49:40 MLD vdr[7425]: [7458] SVDRP MLD > 127.0.0.1:38620 server created
Jun 13 20:49:41 MLD kernel: meson-vdec ff620000.video-decoder: Buffer 9 done but it doesn't exist in m2m_ctx
Jun 13 20:49:41 MLD vdr[7425]: [7812] non blocking file reader thread ended (pid=7425, tid=7812)
Jun 13 20:49:41 MLD kernel: meson-vdec ff620000.video-decoder: Buffer 7 done but it doesn't exist in m2m_ctx

das ist auf einem Odroidn2plus.

Gruß,
  Roland

**Comment by rellla** [comment]
Das Spulen von Aufnahmen funktioniert generell nicht richtig, da tüftle ich gerade ums zu lösen.
Für Amlogic habe ich gerade das Problem, dass ich momentan kein aarch64 LibreELEC zum booten bringe... Das muss ich zuerst lösen.

**Comment by rellla** [comment]
PS: Gerne im VDR-Portal pingen, den issue habe ich nicht mitbekommen ;)

**Comment by rofehr** [comment]
> Das Spulen von Aufnahmen funktioniert generell nicht richtig, da tüftle ich gerade ums zu lösen. Für Amlogic habe ich gerade das Problem, dass ich momentan kein aarch64 LibreELEC zum booten bringe... Das muss ich zuerst lösen.

Kannst ja mal die MLD testen ;)
https://mld6.minidvblinux.de/nightbuild/images/

**Comment by rellla** [comment]
Mld habe ich tatsächlich noch nie drauf in den ganzen Jahren. Wird wohl mal Zeit ;) Jedenfalls läuft das System jetzt wieder und ich schau mir in den nächsten Tagen das Spulen mal an. Besser ist es schon, aber mir fehlt gerade die Zeit, es fertig 
zu machen...

**Comment by rellla** [comment]
Funktioniert das Spulen generell nicht, oder kommt nur die Meldung?
Welche kernel und ffmpeg Version bzw. Quelle nutzt du?

**Comment by rellla** [comment]
That one should be fixed with https://github.com/rellla/vdr-plugin-softhddevice-drm-gles/commit/7c4c9f21ad19b79b4c68ef1ecc7c133356847f00
